apiVersion: apps/v1 
kind: Deployment
metadata:
  name: demucs-worker
spec:
  selector:
    matchLabels:
      app: demucs-worker
  replicas: 2
  template:
    metadata:
      labels:
        app: demucs-worker
    spec:
      containers:
      - name: demucs-worker
        image: yxshwanth/demucs-worker:latest       
        env:
        - name: REDISTOGO_URL
          value: redis.default
        - name: MINIOTOGO_HOST
          value: "minio.default:9000"
        resources:
          requests:
            cpu: 1000m
            memory: 6000Mi

        ports:
        - containerPort: 5000